// Code generated by mockery v1.0.0. DO NOT EDIT.

package kubernetes

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// mockLogStreamProvider is an autogenerated mock type for the logStreamProvider type
type mockLogStreamProvider struct {
	mock.Mock
}

// LogStream provides a mock function with given fields: lineIndex, output
func (_m *mockLogStreamProvider) LogStream(lineIndex uint64, output io.Writer) error {
	ret := _m.Called(lineIndex, output)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, io.Writer) error); ok {
		r0 = rf(lineIndex, output)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *mockLogStreamProvider) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
