#!/usr/bin/env bash

set -o pipefail

GIT_ROOT=$(cd "${BASH_SOURCE%/*}" && git rev-parse --show-toplevel)
ERROR_RESULTS=0

if command -v dockerfile-utils >/dev/null 2>&1; then
    echo "Lint Dockerfiles"
    dockerfiles=$(find "${GIT_ROOT}" -type f -name 'Dockerfile*' -and -not -path "${GIT_ROOT}/vendor/*")
    for f in ${dockerfiles}; do
        f=$(realpath --relative-to="${GIT_ROOT}" "${f}")
        echo "Linting ${f}"
        dockerfile-utils lint "${f}" || ((ERROR_RESULTS++))
    done
else
    echo "dockerfile-utils is missing, please install it from https://github.com/rcjsuen/dockerfile-utils#installation-instructions"
    exit 1
fi

if [ "${ERROR_RESULTS}" -ne 0 ]; then
  echo "✖ ${ERROR_RESULTS} lint test(s) failed. Review the log carefully to see full listing."
  exit 1
else
  echo "✔ Linting passed"
  exit 0
fi
