#!/usr/bin/env bash

set -o pipefail

REPO_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
ERROR_RESULTS=0

if command -v hadolint >/dev/null 2>&1; then
    echo "Lint Dockerfiles" > /dev/stderr
    # NOTE: We don't attempt to lint Windows Dockerfiles since hadolint doesn't recognize (https://github.com/hadolint/hadolint/issues/371)
    # the escape directive (https://docs.docker.com/engine/reference/builder/#escape#escape)
    dockerfiles=$(find "${REPO_ROOT}/dockerfiles" -type f -name 'Dockerfile*' -and -not -name '*servercore*')
    for f in ${dockerfiles}; do
        f=$(realpath --relative-to="${REPO_ROOT}" "${f}")
        echo "Linting ${f}" > /dev/stderr
        hadolint "${f}" || ((ERROR_RESULTS++))
    done
else
    echo "hadolint is missing, please install it from https://github.com/hadolint/hadolint#install" > /dev/stderr
    exit 1
fi

if [ "${ERROR_RESULTS}" -ne 0 ]; then
  echo "✖ ${ERROR_RESULTS} lint test(s) failed. Review the log carefully to see full listing." > /dev/stderr
  exit 1
else
  echo "✔ Linting passed" > /dev/stderr
  exit 0
fi
